## python CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/cytoset
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - deps-dependencies-{{ .Branch }}-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/venv
          key: deps-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            python3 train.py --help
            python test.py --model checkpoints/HEUvsUE_model.pt --config config/model/HEUvsUE/config.json --test_pkl checkpoints/test_HEUvsUE.pkl
        